version: "3"
services:
    gateway-carmind:
      image: fonzeca/gateway-carmind:dev
      ports:
        - "80:80"
        - "443:443"
      networks:
        - carmind
      volumes:
      - ./letsencrypt:/etc/letsencrypt

networks:
  carmind:
    driver: bridge
    name: carmind
    external: true