version: "3"
services:
    gateway-carmind:
      image: fonzeca/gateway-carmind:dev
      ports:
        - "80:80"
      networks:
        - carmind

networks:
  carmind:
    driver: bridge
    name: carmind
    external: true