name: Docker Build and Push

on:
  push:
    branches:
      - dev

env:
    MAIN_TAG: dev

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD_DEV }}

      - name: Build Docker image
        run: docker build \ 
            --tag "fonzeca/${{github.event.repository.name}}:$MAIN_TAG" \
            --tag "fonzeca/${{github.event.repository.name}}:$GITHUB_SHA" \
            .

      - name: Push Docker image to Docker Hub
        run: docker push fonzeca/${{github.event.repository.name}}:dev
