name: Ejemplo de GitHub Action

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    branches: [dev]
    types: 
      - completed

jobs:
  reload_compose:
    name: reload
    runs-on: ubuntu-latest
    steps:
      - name: Paso 2
        run: echo "Este es el paso 2"